### ISSUE TITLE
WinRAR keygen may not work anymore soon

### ISSUE THREAD

**Issue by NicerWritter27** [bitcookies/winrar-keygen#18]
Hey, I don't know if this will be a problem in the future, but I still posted this, take a look at the picture
![image](https://user-images.githubusercontent.com/92959844/204175696-40cd21fb-8e63-42e2-877d-c4e6d45e22bd.png)
It says that some three features are "deprecated" and will be "disabled" soon
I'm not sure if anyone posted this issue before, but just went with it anyways

**Comment by bitcookies** [comment]
These errors may come from [actions/checkout](https://github.com/marketplace/actions/checkout) or [actions/upload-artifact](https://github.com/marketplace/actions/upload-a-build-artifact), because the version used is too old.

It should be solved by updating the version later.

Update later. Thanks 😀

**Comment by bitcookies** [comment]
The workflow has been updated and the warning issue has been resolved. ⛄
